version: '3'

services:
  app:
    image: emppos_instance:v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: emppos_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nivea100
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"